const LayoutConstants = {
    HEADER_HEIGHT: 50,
    ARTICLE_HEADER_HEIGHT: 200,
    FEATURE_BUTTON_SCALE: 0.9,
    FEATURE_BORDER_RADIUS: 10,
    FEATURE_BUTTON_HEIGHT: 145
}

export { LayoutConstants }